"""create initial tables

Revision ID: 57240da50d2f
Revises: affd4ef2b72a
Create Date: 2025-05-24 00:22:38.947616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57240da50d2f'
down_revision: Union[str, None] = 'affd4ef2b72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_index('ix_clients_password', table_name='clients')
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_clients_password', 'clients', ['password'], unique=True)
    op.drop_column('clients', 'hashed_password')
    # ### end Alembic commands ###
