"""create initial tables

Revision ID: 5ea81169ed06
Revises: 57240da50d2f
Create Date: 2025-05-24 00:25:53.783377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea81169ed06'
down_revision: Union[str, None] = '57240da50d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.drop_index('ix_clients_cpf', table_name='clients')
    op.drop_constraint('uq_client_cpf', 'clients', type_='unique')
    op.drop_constraint('uq_client_email', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_client_email', 'clients', ['email'])
    op.create_unique_constraint('uq_client_cpf', 'clients', ['cpf'])
    op.create_index('ix_clients_cpf', 'clients', ['cpf'], unique=True)
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.drop_column('clients', 'is_admin')
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
