"""create initial tables

Revision ID: bfc7124d694b
Revises: 5ea81169ed06
Create Date: 2025-05-24 00:34:10.418720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc7124d694b'
down_revision: Union[str, None] = '5ea81169ed06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'cpf',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###
